### ISSUE TITLE
Special Pick Scores

### ISSUE THREAD

**Issue by Joi179** [JustinReiter/WarLight.AI#16]
Caucasus -50
West China -50
Australia -25 when Antarctica isnt Wastelanded
- - - - - - - - - - - - - - - - - - - - - - - -
South Pole being Pickable and Antarctica not being an FTB -1
Mexico Pickable and Central America not being an FTB -1
when "Iceland" or "Qaanaaq" are pickable in Greenland -5

**Comment by Joi179** [comment]
Dont start with anything that is below the line.

**Comment by JustinReiter** [comment]
Completed top half of comment with lowering score if bonus is Caucasus or West China. Have also implemented logic concerning Australia and Ant. Closing issue for now, and once the bottom half is resolved, open the issue back up.

**Comment by JustinReiter** [comment]
Already implemented logic to cover a bonus taking 3+ turns to take so greenland is satisfied. Did add a -10 score to Greenland if Nord or Itseqqortoormiit or picked due to not being completed in 2 turns.

~~Will need to add similar logic to Australia.~~

**Comment by niklasr8** [comment]
Caucasus and WC are such nice bonuses :(
I suggest to add some logic to check whether they are pickable.
