### ISSUE TITLE
Sub Combo's

### ISSUE THREAD

**Issue by Joi179** [JustinReiter/WarLight.AI#22]
A "Sub Combo" is a Combo that either require **an** +5 to pick or is a combo **on** a +3.
It should only go for "Sub Combo's" if there are no other Combo's on the board.

**Comment by JustinReiter** [comment]
Implemented code to follow certain list of priority:

(1) Combos with no counters
(2) Sub Combos with no counters
(3) Combos with 1+ counters
(4) sub combos with 1+ counters

**Comment by JustinReiter** [comment]
Merged branch into master and appears to work fully.
