### ISSUE TITLE
Counter FTB / FTB Pick Order

### ISSUE THREAD

**Issue by Joi179** [JustinReiter/WarLight.AI#5]
It should always pick in this order

1: Pick That has a Double Border on the FTB
2: The FTB pick Itself
3: Pick that has a Single Border on the FTB

**Comment by JustinReiter** [comment]
From #6:

> It should pick a combo in this order.
> 1: Pick that has a double / tripple border on the comboable bonus
> 2: The Bonus itself
> 3: Pick that has a single border on the comboable bonus

**Comment by JustinReiter** [comment]
Completed single function to reorder support and main pick in ComboBonuses. Need to perform tests to ensure that there is no unintended collision with the final reorder of picks.
