### ISSUE TITLE
Combo Bonus Check

### ISSUE THREAD

**Issue by Joi179** [JustinReiter/WarLight.AI#6]
Check if the comboed Bonus is a 2 turn take
Check if the other Pick (In this Case West Africa) is not a 3turn else its a Bad Combo
![Bad Combo](https://user-images.githubusercontent.com/33321958/60380415-ae590000-9a45-11e9-9cc1-fd368db30777.PNG)
A Potential Bug created by the same 2 picks creating 2 Comboable Bonuses
![Potential Bug](https://user-images.githubusercontent.com/33321958/60380430-c92b7480-9a45-11e9-803d-ccb35dd50d6b.PNG)

**Comment by Joi179** [comment]
It should pick a combo in this order.
1: Pick that has a double / tripple border on the comboable bonus
2: The Bonus itself
3: Pick that has a single border on the comboable bonus

**Comment by JustinReiter** [comment]
Completed the first part of the issue. Will address the second part of the issue with ordering of picks in #5

**Comment by Joi179** [comment]
It should also pick in a Combo the smaller Bonus first.

**Comment by JustinReiter** [comment]
Added in function for sorting useful and extra picks (separately) by the number of bordering territories.
